### ISSUE TITLE
Hi~ 关于您申请的萌ICP备案问题

### ISSUE THREAD

**Issue by MisakaShell** [ember-L/ember-L.github.io#1]
你好：ember-L
你在萌国申请的萌ICP备案，自24hour 仍未对接萌ICP备案地址，请进行对接，谢谢。

**Comment by MisakaShell** [comment]
不好意思啊，您的对接时间太久了被bot自动回收掉了，您可以在此申请一下：https://icp.gov.moe/join.php?id=20236033

**Comment by MisakaShell** [comment]
如果申请完毕您可，回复一下我或者关闭这个issue，谢谢

**Comment by ember-L** [comment]
好的
